### ISSUE TITLE
Can someone please explain why I'm getting type error while deploying?

### ISSUE THREAD

**Issue by Jaseempk** [PatrickAlphaC/hardhat-smartcontract-lottery-fcc#108] opened 2022-10-26 02:02 UTC
I'm getting the following error while deploying my contract:
Error: ERROR processing skip func of /home/jaseempk/hh-fcc/hardhat-smartcontract-raffle-fcc/deploy/00-deploy-mock.js:
TypeError: Cannot read properties of undefined (reading 'utils')
    at Object.<anonymous> (/home/jaseempk/hh-fcc/hardhat-smartcontract-raffle-fcc/helper-hardhat-config.js:13:21)
The thing is that I'm not getting any errors while compiling, but once I try to deploy them then I'm getting these errors and even after spending a lot of time I'm still stuck here being not able to deploy them...can anyone please help me??

**Comment by ade-hardhat** [comment] 2022-11-01 17:01
Error seems to be coming from your `helper-hardhat-config.js` file. Can you post the script?

**Comment by Jaseempk** [comment] 2022-11-17 01:02
@krakxn 
![Screenshot 2022-11-17 062617](https://user-images.githubusercontent.com/99121494/202327900-999ff98f-7832-47ec-917a-9cf824783b00.png)
@krakxn earlier I got this issue and after spending way lotta time on it I thought it might be because of some errors in the WSL set-up so I uninstalled everything and reinstalled it now, also I created all the code from scratch but still when I'm deploying I'm getting this error, but I'm able to compile everything successfully.

**Comment by Jaseempk** [comment] 2022-11-17 01:03
![Screenshot 2022-11-17 063309](https://user-images.githubusercontent.com/99121494/202328636-c3ca7699-2188-4fa1-b56d-a41cd93fd092.png)

**Comment by Jaseempk** [comment] 2022-11-18 01:45
@alymurtazamemon can you please take a moment to look into these?

**Comment by alymurtazamemon** [comment] 2022-11-18 02:03
@Jaseempk Please provide your repo link, issue is in the `00-deploy-raffle.js` file, I think you are missing to import `ethers` and reading the `utils` property of it.

**Comment by Jaseempk** [comment] 2022-11-18 02:16
![Screenshot 2022-11-18 074341](https://user-images.githubusercontent.com/99121494/202601149-5ab30141-abc4-4300-bea6-b402b97f971e.png)
![Screenshot 2022-11-18 074410](https://user-images.githubusercontent.com/99121494/202601155-bab2b6b7-f1fa-4120-834c-ca2e176ef4cf.png)
@alymurtazamemon this is what my `deploy-raffle.js` looks like, I can't provide you the repo link for that as I haven't pushed them to GitHub yet

**Comment by alymurtazamemon** [comment] 2022-11-18 02:20
@Jaseempk You can push and leave a repo link.

**Comment by Jaseempk** [comment] 2022-11-18 03:52
@alymurtazamemon  this is the repo link:
[](url:https://github.com/Jaseempk/hardhat-smartcontract-raffle)
https://github.com/Jaseempk/hardhat-smartcontract-raffle

**Comment by alymurtazamemon** [comment] 2022-11-18 05:05
@Jaseempk As you can see below in the image, I have fixed your code and deployed it, this guarantees you that this is not course related issue.

Now I can push this fixed code to your repo but I will not do this because your project had tons of issues (I cannot even write each here) that tell you did not completely get things in this lesson. So I would recommend you spend some time with this lesson, rewatch things, rewrite the code or identify the issues in already written code.

I am closing this issue, feel free to open it again or come to a discussions tab because you can see this is not course related issue.

closing #108

<img width="1470" alt="Screenshot 2022-11-18 at 9 59 01 AM" src="https://user-images.githubusercontent.com/56123405/202621267-84e24765-e985-422c-873d-cee0ae6048d6.png">

**Comment by Jaseempk** [comment] 2022-11-18 05:18
@alymurtazamemon thanks for letting me know, is the problem only for `deploy-raffle.js` or there is a problem with my `Raffle.sol` also?

**Comment by alymurtazamemon** [comment] 2022-11-18 05:22
>  @alymurtazamemon thanks for letting me know, is the problem only for `deploy-raffle.js` or there is a problem with my `Raffle. sol` also?

No, your contracts do not have any problem, the problem is in your deploy file, hardhar.config.js file, helper file, and package.json file.

**Comment by Jaseempk** [comment] 2022-11-19 04:48
@alymurtazamemon can you please tell me what all changes I have to make in `package.json` and `hardhat.config.js` files ,others I will find my own

**Comment by alymurtazamemon** [comment] 2022-11-19 07:54
@Jaseempk add this `"@nomiclabs/hardhat-waffle": "^2.0.3",` and add this in hardhat config file `require("@nomiclabs/hardhat-waffle");`

**Comment by Jaseempk** [comment] 2022-11-20 05:54
@alymurtazamemon I have added Ethereum-waffle, but still getting another error, which I have posted as a new discussion.

**Closed** 2022-11-20 05:55 UTC
